# Generated by Django 5.2.3 on 2025-08-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.FloatField(default=0),
        ),
    ]
